# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Doable CI

on:
  push:
    branches: ["master", "main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Set env variables in .env
        run: echo "PORT=${{secrets.PORT}}" >> .env

      # Check if pm2 process with name 'doable' exists
      - name: Check if pm2 process exists
        id: pm2_check
        run: pm2 list | grep -q "doable" || echo "::set-output name=exists::false"

      # Stop pm2 process if it exist
      - name: Stop pm2 process
        if: steps.pm2_check.outputs.exists == 'true'
        run: pm2 stop doable

      # Access client folder
      - name: Access client folder
        run: cd client

      # Install npm packages
      - name: Install npm packages
        run: npm i

      # Run the build
      - name: Build for production
        run: npm run build --if-present

      # Return to root folder
      - name: Return to root folder
        run: cd ..

      # Start pm2 process if it doesn't exist
      - name: Start pm2 process
        if: steps.pm2_check.outputs.exists == 'false'
        run: pm2 start npm --name doable -- start

      # Save pm2 process if it did not exist for system reboot
      - name: Save pm2 process
        if: steps.pm2_check.outputs.exists == 'false'
        run: pm2 save

      # Restart pm2 process
      - name: Restart pm2 process
        run: pm2 restart doable
